### PR TITLE
Improve user interaction with slider timeline

### PR DESCRIPTION
**Pull request by azfoo**
Slider UI shows the potential for being dragged to seek time.
Added open hand cursor to slider trough that becomes closed when clicked on.

### CODE REVIEW

**Review by FelipeDefensor — CHANGES_REQUESTED** [review]
Giving visual feedback for the interactivity of the trough is good and you got the mixin right, but I think the open hand cursor looks bad. Its too big compared to other UI elements and it has an outdated feel to it. The pointing hand cursor looks much better, in my opinion, and could be used both for the dragging and non-dragging state. What do you think?

**Comment by FelipeDefensor** [comment]
On 41ab0b9 I also added some interactivity to the line, which is something that I've seen users expect when trying out TiLiA.

**Comment by azfoo** [comment]
> The pointing hand cursor looks much better, in my opinion, and could be used both for the dragging and non-dragging state. What do you think?

I think the cursors should show standardised interaction across the different timelines. Perhaps the pointing hand if there is something inspectable? In this case, perhaps the horizontal arrows might be better.

**Comment by FelipeDefensor** [comment]
> > The pointing hand cursor looks much better, in my opinion, and could be used both for the dragging and non-dragging state. What do you think?
> 
> I think the cursors should show standardised interaction across the different timelines. Perhaps the pointing hand if there is something inspectable? In this case, perhaps the horizontal arrows might be better.

Fair point. The horizontal arrows look a bit out of place for me here, but it might be just that I'm not used to them yet. Let's go with them.

**Comment by azfoo** [comment]
I'll go ahead and check all of the cursors then. 
On that point, would it be fair to make the hierarchy posts have the same horizontal arrows for cursors? It would make it more apparent that the blocks are sizeable that way too.

**Comment by FelipeDefensor** [comment]
> > > The pointing hand cursor looks much better, in my opinion, and could be used both for the dragging and non-dragging state. What do you think?
> > 
> > 
> > I think the cursors should show standardised interaction across the different timelines. Perhaps the pointing hand if there is something inspectable? In this case, perhaps the horizontal arrows might be better.
> 
> Fair point. The horizontal arrows look a bit out of place for me here, but it might be just that I'm not used to them yet. Let's go with them.

Ok, so I think I get why the horizontal arrow cursor bothers. It's because we're used to it indicating to *edges* that are draggable, which is not the case here. I say we go with this for now and try to get some user feedback, but let's consider modifying the trough drawing when its hovered instead of changing the cursor as an alternative.

**Comment by FelipeDefensor** [comment]
Also, let's squash the first three commits.

**Review by FelipeDefensor — APPROVED** [review]

**Pull request merged**
